package com.myspace.insurancepolicyrulestoringresponse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Insurance implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int id;
	private double annual_income;
	private int age;
	private java.lang.String occupation;
	private double premium_amount;
	private java.lang.String medical_history;

	private int statusunique_ID;

	private java.lang.String statusAnnualIncome;

	private java.lang.String statusAge;

	private java.lang.String statusOccupation;

	private java.lang.String statusPremiumAmount;

	private java.lang.String statusMedical_History;

	private java.lang.String finalstatus;

	private java.lang.String name;

	private java.lang.String statusname;

	public Insurance() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public java.lang.String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(java.lang.String occupation) {
		this.occupation = occupation;
	}

	public java.lang.String getMedical_history() {
		return this.medical_history;
	}

	public void setMedical_history(java.lang.String medical_history) {
		this.medical_history = medical_history;
	}

	public int getStatusunique_ID() {
		return this.statusunique_ID;
	}

	public void setStatusunique_ID(int statusunique_ID) {
		this.statusunique_ID = statusunique_ID;
	}

	public java.lang.String getStatusAnnualIncome() {
		return this.statusAnnualIncome;
	}

	public void setStatusAnnualIncome(java.lang.String statusAnnualIncome) {
		this.statusAnnualIncome = statusAnnualIncome;
	}

	public java.lang.String getStatusAge() {
		return this.statusAge;
	}

	public void setStatusAge(java.lang.String statusAge) {
		this.statusAge = statusAge;
	}

	public java.lang.String getStatusOccupation() {
		return this.statusOccupation;
	}

	public void setStatusOccupation(java.lang.String statusOccupation) {
		this.statusOccupation = statusOccupation;
	}

	public java.lang.String getStatusPremiumAmount() {
		return this.statusPremiumAmount;
	}

	public void setStatusPremiumAmount(java.lang.String statusPremiumAmount) {
		this.statusPremiumAmount = statusPremiumAmount;
	}

	public java.lang.String getStatusMedical_History() {
		return this.statusMedical_History;
	}

	public void setStatusMedical_History(java.lang.String statusMedical_History) {
		this.statusMedical_History = statusMedical_History;
	}

	public java.lang.String getFinalstatus() {
		return this.finalstatus;
	}

	public void setFinalstatus(java.lang.String finalstatus) {
		this.finalstatus = finalstatus;
	}

	public double getAnnual_income() {
		return this.annual_income;
	}

	public void setAnnual_income(double annual_income) {
		this.annual_income = annual_income;
	}

	public double getPremium_amount() {
		return this.premium_amount;
	}

	public void setPremium_amount(double premium_amount) {
		this.premium_amount = premium_amount;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getStatusname() {
		return this.statusname;
	}

	public void setStatusname(java.lang.String statusname) {
		this.statusname = statusname;
	}

	public Insurance(int id, double annual_income, int age,
			java.lang.String occupation, double premium_amount,
			java.lang.String medical_history, int statusunique_ID,
			java.lang.String statusAnnualIncome, java.lang.String statusAge,
			java.lang.String statusOccupation,
			java.lang.String statusPremiumAmount,
			java.lang.String statusMedical_History,
			java.lang.String finalstatus, java.lang.String name,
			java.lang.String statusname) {
		this.id = id;
		this.annual_income = annual_income;
		this.age = age;
		this.occupation = occupation;
		this.premium_amount = premium_amount;
		this.medical_history = medical_history;
		this.statusunique_ID = statusunique_ID;
		this.statusAnnualIncome = statusAnnualIncome;
		this.statusAge = statusAge;
		this.statusOccupation = statusOccupation;
		this.statusPremiumAmount = statusPremiumAmount;
		this.statusMedical_History = statusMedical_History;
		this.finalstatus = finalstatus;
		this.name = name;
		this.statusname = statusname;
	}

}